# Generated by Django 2.0.2 on 2019-04-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='max_stocks_sell',
            field=models.IntegerField(default=100),
        ),
    ]
