# Generated by Django 2.0.2 on 2019-04-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20190411_0443'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCMPRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmp', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=True, to='market.Company')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
