# Generated by Django 2.0.2 on 2019-04-13 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_company_max_stocks_sell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='temp_stocks_bought',
        ),
        migrations.RemoveField(
            model_name='company',
            name='temp_stocks_sold',
        ),
    ]
