# Generated by Django 2.0.2 on 2019-04-19 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20190414_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycmprecord',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Company'),
        ),
        migrations.AlterField(
            model_name='investmentrecord',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Company'),
        ),
        migrations.AlterField(
            model_name='investmentrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Company'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
