# Generated by Django 2.0.2 on 2019-05-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_transactionscheduler'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionscheduler',
            options={'ordering': ['-mode', 'timestamp']},
        ),
        migrations.RemoveField(
            model_name='company',
            name='max_stocks_sell',
        ),
        migrations.RemoveField(
            model_name='company',
            name='stocks_offered',
        ),
        migrations.RemoveField(
            model_name='company',
            name='stocks_remaining',
        ),
        migrations.AddField(
            model_name='company',
            name='stocks_bought',
            field=models.IntegerField(default=0),
        ),
    ]
