# Generated by Django 2.0.2 on 2019-05-07 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_transactionscheduler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionscheduler',
            name='company',
        ),
        migrations.RemoveField(
            model_name='transactionscheduler',
            name='user',
        ),
        migrations.DeleteModel(
            name='TransactionScheduler',
        ),
    ]
