# Generated by Django 2.0.2 on 2019-05-10 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_auto_20190508_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionscheduler',
            options={'ordering': ['timestamp']},
        ),
    ]
