# Generated by Django 2.0.2 on 2019-04-12 00:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=Decimal('10000'), max_digits=20),
        ),
        migrations.AddField(
            model_name='user',
            name='coeff_of_variation',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
