# Generated by Django 2.0.2 on 2019-04-12 01:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190412_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=Decimal('12000'), max_digits=20),
        ),
    ]
