# Generated by Django 2.0.2 on 2019-04-13 15:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190413_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loan',
            field=models.DecimalField(decimal_places=2, default=Decimal('5000'), max_digits=20),
        ),
        migrations.AddField(
            model_name='user',
            name='loan_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='loan_count_absolute',
            field=models.IntegerField(default=1),
        ),
    ]
