# Generated by Django 2.0.2 on 2019-04-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190419_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='news_count',
            field=models.IntegerField(default=1),
        ),
    ]
