# Generated by Django 2.0.2 on 2019-04-21 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_news_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='news_count',
        ),
    ]
