# Generated by Django 2.0.2 on 2019-04-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocksdatabase',
            name='pointer',
            field=models.IntegerField(default=0),
        ),
    ]
