# Generated by Django 2.0.2 on 2019-04-20 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20190417_2103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocksdatabase',
            options={'ordering': ['company', 'pointer']},
        ),
    ]
