# Generated by Django 2.0.2 on 2019-04-20 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20190420_1502'),
        ('stocks', '0003_auto_20190419_2008'),
    ]

    operations = [
    ]
