# Generated by Django 2.0.2 on 2019-05-11 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_auto_20190510_2118'),
        ('stocks', '0004_merge_20190420_1654'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stocksdatabase',
            unique_together={('company', 'pointer')},
        ),
    ]
